# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\code\software_engineer\Shudo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\code\software_engineer\Shudo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\code\software_engineer\Shudo\CMakeFiles E:\code\software_engineer\Shudo\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\code\software_engineer\Shudo\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_shudu

# Build rule for target.
test_shudu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_shudu
.PHONY : test_shudu

# fast build rule for target.
test_shudu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_shudu.dir\build.make CMakeFiles/test_shudu.dir/build
.PHONY : test_shudu/fast

src/shudu.obj: src/shudu.cpp.obj
.PHONY : src/shudu.obj

# target to build an object file
src/shudu.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_shudu.dir\build.make CMakeFiles/test_shudu.dir/src/shudu.cpp.obj
.PHONY : src/shudu.cpp.obj

src/shudu.i: src/shudu.cpp.i
.PHONY : src/shudu.i

# target to preprocess a source file
src/shudu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_shudu.dir\build.make CMakeFiles/test_shudu.dir/src/shudu.cpp.i
.PHONY : src/shudu.cpp.i

src/shudu.s: src/shudu.cpp.s
.PHONY : src/shudu.s

# target to generate assembly for a file
src/shudu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_shudu.dir\build.make CMakeFiles/test_shudu.dir/src/shudu.cpp.s
.PHONY : src/shudu.cpp.s

src/shudu_unittest.obj: src/shudu_unittest.cpp.obj
.PHONY : src/shudu_unittest.obj

# target to build an object file
src/shudu_unittest.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_shudu.dir\build.make CMakeFiles/test_shudu.dir/src/shudu_unittest.cpp.obj
.PHONY : src/shudu_unittest.cpp.obj

src/shudu_unittest.i: src/shudu_unittest.cpp.i
.PHONY : src/shudu_unittest.i

# target to preprocess a source file
src/shudu_unittest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_shudu.dir\build.make CMakeFiles/test_shudu.dir/src/shudu_unittest.cpp.i
.PHONY : src/shudu_unittest.cpp.i

src/shudu_unittest.s: src/shudu_unittest.cpp.s
.PHONY : src/shudu_unittest.s

# target to generate assembly for a file
src/shudu_unittest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_shudu.dir\build.make CMakeFiles/test_shudu.dir/src/shudu_unittest.cpp.s
.PHONY : src/shudu_unittest.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... test_shudu
	@echo ... src/shudu.obj
	@echo ... src/shudu.i
	@echo ... src/shudu.s
	@echo ... src/shudu_unittest.obj
	@echo ... src/shudu_unittest.i
	@echo ... src/shudu_unittest.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

